version: 2
updates:
    - package-ecosystem: github-actions
      directory: /
      allow:
          - dependency-type: all
      schedule:
          interval: monthly
      pull-request-branch-name:
          separator: "-"
    - package-ecosystem: composer
      directory: /
      versioning-strategy: increase
      allow:
          - dependency-type: all
      schedule:
          interval: monthly
      pull-request-branch-name:
          separator: "-"
