name: tests
on:
    pull_request: ~
    push:
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
    tests:
        runs-on: ubuntu-latest
        name: tests
        strategy:
            matrix:
                install-args: ['', '--prefer-lowest']
                php-version: ['8.1', '8.2', '8.3', '8.4']
            fail-fast: false
        steps:
            - name: checkout
              uses: actions/checkout@v5

            - name: php
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "${{ matrix.php-version }}"
                  tools: composer:v2

            - name: composer
              uses: ramsey/composer-install@v3
              with:
                  composer-options: "--prefer-dist ${{ matrix.install-args }}"

            - name: phpunit
              run: |
                  vendor/bin/phpunit

            - name: phpstan-cache
              uses: actions/cache@v4
              with:
                  key: phpstan-${{ github.ref }}-${{ github.sha }}
                  path: .phpstan-cache
                  restore-keys: |
                      phpstan-${{ github.ref }}-
                      phpstan-

            - name: phpstan
              run: |
                  mkdir -p .phpstan-cache
                  vendor/bin/phpstan analyse --no-progress --no-interaction
