name: tests
on:
    pull_request: ~
    push:
        branches:
            - main

jobs:
    tests:
        runs-on: ubuntu-latest
        name: tests
        strategy:
            matrix:
                install-args: ['', '--prefer-lowest']
                php-version: ['7.4', '8.0', '8.1']
            fail-fast: false
        steps:
            - name: cancel
              uses: styfle/cancel-workflow-action@0.10.0
              with:
                  access_token: ${{ github.token }}

            - name: checkout
              uses: actions/checkout@v3

            - name: php
              uses: shivammathur/setup-php@2.21.2
              with:
                  php-version: "${{ matrix.php-version }}"
                  tools: composer:v2

            - name: composer
              uses: ramsey/composer-install@2.1.0
              with:
                  composer-options: "--prefer-dist ${{ matrix.install-args }}"

            - name: phpunit
              run: |
                  vendor/bin/phpunit

            - name: phpstan-cache
              uses: actions/cache@v3.0.8
              with:
                  key: phpstan-${{ github.ref }}-${{ github.sha }}
                  path: .phpstan-cache
                  restore-keys: |
                      phpstan-${{ github.ref }}-
                      phpstan-

            - name: phpstan
              run: |
                  mkdir -p .phpstan-cache
                  vendor/bin/phpstan analyse --no-progress --no-interaction
